name: Build All Targets

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Grant write permissions globally so called reusable workflows can use them
permissions:
  contents: write
  actions: write

jobs:
  build-windows:
    uses: ./.github/workflows/reusable-build.yml
    permissions:
      contents: write
      actions: write
    with:
      name: Windows
      os: windows-latest
      buildArgs: windows
      artifactName: A-Slice-Windows
      artifactPath: export/release/windows/bin/
      cachePath: cache-windows
      cacheLibrariesPath: cache-haxelib
      exportPath: windows

  build-linux:
    uses: ./.github/workflows/reusable-build.yml
    permissions:
      contents: write
      actions: write
    with:
      name: Linux
      os: ubuntu-latest
      buildArgs: linux
      artifactName: A-Slice-Linux
      artifactPath: export/release/linux/bin/
      cachePath: cache-linux
      cacheLibrariesPath: cache-haxelib
      exportPath: linux

  build-macos:
    uses: ./.github/workflows/reusable-build.yml
    permissions:
      contents: write
      actions: write
    with:
      name: macOS
      os: macos-latest
      buildArgs: macos
      artifactName: A-Slice-macOS
      artifactPath: export/release/macos/bin/
      cachePath: cache-macos
      cacheLibrariesPath: cache-haxelib
      exportPath: macos

  build-android:
    uses: ./.github/workflows/reusable-build.yml
    permissions:
      contents: write
      actions: write
    with:
      name: Android
      os: ubuntu-latest
      buildArgs: android
      artifactName: A-Slice-Android
      artifactPath: export/release/android/bin/
      cachePath: cache-android
      cacheLibrariesPath: cache-haxelib
      exportPath: android

  build-ios:
    uses: ./.github/workflows/reusable-build.yml
    permissions:
      contents: write
      actions: write
    with:
      name: iOS
      os: macos-latest
      buildArgs: ios
      artifactName: A-Slice-iOS
      artifactPath: export/release/ios/bin/
      cachePath: cache-ios
      cacheLibrariesPath: cache-haxelib
      exportPath: ios
