# A-Slice Issue Report

version: ""

report:
type: "" # Bug / Crash / Feature / Feedback
title: ""
description: ""

environment:
operating_system: ""
device: ""
architecture: ""
additional_info: ""

bug_details:
steps_to_reproduce:
- ""
- ""
- ""

expected_behavior: ""
actual_behavior: ""

crash_details:
crashed: false
crash_logs: |
Paste crash logs here.

error_message: ""

feature_request:
requested_feature: ""
problem_it_solves: ""
additional_details: ""

feedback:
message: ""

attachments:
screenshots: []
videos: []
other_files: []

additional_information: ""

contact:
username: ""
preferred_contact: ""
